### ISSUE TITLE
Change all instances of Logger through the app to be Singleton model

### ISSUE THREAD

**Issue by cereallarceny** [OpenMined/syft.js#108]
We don't need to pass the `Logger` class as an argument to functions anywhere. Simply create this using `new Logger()` wherever needed. Change this in all associated files that use the `Logger` class

**Comment by rav7kantsingh** [comment]
I would  like to work on this issue.

**Comment by cereallarceny** [comment]
Go for it @IamRavikantSingh

**Comment by rav7kantsingh** [comment]
I think all the loggers are already changed. I searched logger and found that every file is already using logger with `new Logger()`

**Comment by cereallarceny** [comment]
In which PR?

**Comment by rav7kantsingh** [comment]
> In which PR?

https://github.com/OpenMined/syft.js/pull/106

**Comment by cereallarceny** [comment]
👍
