### ISSUE TITLE
Demo Website

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/syft.js#12]
In a folder "demo", create a demo website which imports syft.js and executes a function contained within syft.js. This website obviously won't do much yet (except import a library) but the idea is that it will eventually grow into our Federated Learning App.

**Comment by TanayGahlot** [comment]
I will take this up.

**Comment by iamtrask** [comment]
https://github.com/OpenMined/syft.js/pull/20#pullrequestreview-139786445
