### ISSUE TITLE
Create a better Readme

### ISSUE THREAD

**Issue by cereallarceny** [OpenMined/syft.js#120]
[Based on this readme template](https://github.com/OpenMined/.github/blob/master/README-TEMPLATE.md), we should improve our readmes across all OpenMined projects.

More specifically, you should fill out the template **at the minimum**.

- [x] Don't worry about the logo, I'll get this to you.
- [x] Change all badges to reflect your repo, include other badges as desired, but use those at the minimum. You can generate more here: https://shields.io/
- [x] Change the title
- [x] Write a detailed description of what your library intends to accomplish. I would also advise that you provide links to the following papers: https://ai.googleblog.com/2017/04/federated-learning-collaborative.html, https://arxiv.org/pdf/1902.01046.pdf, https://research.google/pubs/pub47246/. I would also explain that the system is driven by developing a model in PySyft, hosting it in PyGrid, and then downloading it using a worker library. Be sure to also link to the other worker libraries that aren't yours, so we can cross-promote our work!
- [x] Fill out a list of features that your library supports. A suggested list includes: PySyft plan execution, optional third-party JWT authentication, wifi detection, charge detection, sleep/wake detection, protocols for secure aggregation (put mark this as "in progress"), and a list of environments this library is expected to work in. That's a short list, you can add or remove what you please.
- [x] Installation section should be updated and specify the appropriate package manager (with a link to our deployment page on that package manager)
- [x] Usage section should be comprised of the implementation code for the MNIST example. Make sure to clean these up first. I've created an issue for this elsewhere - do that one first.
- [x] Fill out some basic contributing information to tell people how to run your library locally, what the local development instructions are, etc.
- [x] Fill out the list of contributors from All Contributors. Build this into your workflow and expect to use their Github issue commands in the future to make adding people to the readme easier.

**Comment by vvmnnnkv** [comment]
Let's try updating readme now
@all-contributors please add @cereallarceny for ideas, code, design, doc, business
