### ISSUE TITLE
Create an auto-generated API reference documentation

### ISSUE THREAD

**Issue by cereallarceny** [OpenMined/syft.js#122]
## Where?
The entire project

## Who?
Developers looking to implement the library in their application.

## What?
We want to provide automatically generated API reference documentation to allow developers to use our library in their application to be able to read all publicly available methods and their signatures. This documentation is purely meant to be functional. It does not need to look pretty, but it does need to be **very** organized. [Here is an example of what you should aim to reproduce.](https://github.com/christinecha/choreographer-js#full-api-reference)

## Additional Context
- [x] Generate this file to the root of the project located at `/API-REFERENCE.md`
- [x] Set it to run the regeneration function on every commit and add it to the current commit
- [x] **Add a reference to this file from the `Usage` section of the main readme**

**Comment by vvmnnnkv** [comment]
Done in https://github.com/OpenMined/syft.js/pull/153
