### ISSUE TITLE
Test all major features

### ISSUE THREAD

**Issue by cereallarceny** [OpenMined/syft.js#123]
## Description
We want to test all major features of the federated learning process in this repo. This includes:

- [x] Mocking PyGrid in order to run the test suite without the use of another server running ([these endpoints will likely be what you want to mock](https://github.com/OpenMined/PyGrid/issues/445))
- [x] Testing a flow with no authentication
- [x] Testing a flow with basic JWT authentication (failing)
- [x] Testing a flow with basic JWT authentication (passing)
- [x] Testing the acceptance of a worker in an FL cycle request
- [x] Testing the timeout for the re-application of an FL cycle request
- [x] Testing the graceful handling of an error whereby a plan or model does not exist in PyGrid from what is being requested
- [x] Testing the creation of one job
- [x] Testing the creation of multiple jobs
- [x] Testing that a job can be completed successfully
- [x] Testing that multiple jobs can be completed successfully
- [x] Testing that errors in a job can be caught by the `onError` handler and handled appropriately
- [x] Testing that we can successfully report a model diff to PyGrid
- Any other related tests, or permutations of the above tests, that are required to pass for a developer to successfully use this library... **in other words, be thorough and test everything you can think of that a developer might do.**

## Type of Test
- [ ] **Unit test** (e.g. checking a loop, method, or function is working as intended)
- [x] **Integration test** (e.g. checking if a certain group or set of functionality is working as intended)
- [ ] **Regression test** (e.g. checking if by adding or removing a module of code allows other systems to continue to function as intended)
- [ ] **Stress test** (e.g. checking to see how well a system performs under various situations, including heavy usage)
- [ ] **Performance test** (e.g. checking to see how efficient a system is as performing the intended task)
- [ ] Other...

## Expected Behavior
We expect all the above tests to pass.

## Additional Context
None

**Comment by vvmnnnkv** [comment]
Done in #170
