### ISSUE TITLE
Write inline documentation for src/grid-api-client.js

### ISSUE THREAD

**Issue by tcp** [OpenMined/syft.js#124]
## Where?
[src/grid-api-client.js](https://github.com/OpenMined/syft.js/blob/master/src/grid-api-client.js)

## Who?

Any developer who wants to work on syft.js should be able to read inline documentation for this file, as well as any file in the project.

## What?
We need to go "line-by-line" and create inline documentation for this file. Please try to use proper punctuation and English grammar to the best of your ability.

## Additional Context
None

**Comment by thefirebanks** [comment]
Hello! If these inline documentation issues still need someone to work on I'd be happy to take on the task!

**Comment by cereallarceny** [comment]
Do it @thefirebanks! Send us some PR's and we'll check it out.
