### ISSUE TITLE
Write inline documentation for src/job.js

### ISSUE THREAD

**Issue by tcp** [OpenMined/syft.js#125]
## Where?
[src/job.js](https://github.com/OpenMined/syft.js/blob/master/src/job.js)

## Who?

Any developer who wants to work on syft.js should be able to read inline documentation for this file, as well as any file in the project.

## What?
We need to go "line-by-line" and create inline documentation for this file. Please try to use proper punctuation and English grammar to the best of your ability.

## Additional Context
None

**Comment by nahuakang** [comment]
Will take a look at this one tonight to see if there's additional edits required.

**Comment by vvmnnnkv** [comment]
Done! Thanks @nahuakang!
