### ISSUE TITLE
Write inline documentation for src/sockets.js

### ISSUE THREAD

**Issue by tcp** [OpenMined/syft.js#127]
## Where?
[src/sockets.js](https://github.com/OpenMined/syft.js/blob/master/src/sockets.js)

## Who?

Any developer who wants to work on syft.js should be able to read inline documentation for this file, as well as any file in the project.

## What?
We need to go "line-by-line" and create inline documentation for this file. Please try to use proper punctuation and English grammar to the best of your ability.

## Additional Context
None

**Comment by nahuakang** [comment]
For documentation, I think I'll move on to this one so that I can familiarize myself enough to cover the corresponding unittest issue for `sockets.js`.

**Comment by cereallarceny** [comment]
Perfect - it's yours @nahuakang !
