### ISSUE TITLE
Write inline documentation for src/types/placeholder.js

### ISSUE THREAD

**Issue by tcp** [OpenMined/syft.js#134]
## Where?
[src/types/placeholder.js](https://github.com/OpenMined/syft.js/blob/master/src/types/placeholder.js)

## Who?

Any developer who wants to work on syft.js should be able to read inline documentation for this file, as well as any file in the project.

## What?
We need to go "line-by-line" and create inline documentation for this file. Please try to use proper punctuation and English grammar to the best of your ability.

## Additional Context
None

**Comment by cereallarceny** [comment]
Closed by https://github.com/OpenMined/syft.js/pull/208
