### ISSUE TITLE
Add gpu.js as a dependency

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/syft.js#14]
In the long run, we will very likely want to use a separate tensor library for all our javascript tensor operation needs. The first one we'd like to evaluate is gpu.js (http://gpu.rocks/). So, to start, this issue is to import that library in as a dependency.

**Comment by k105la** [comment]
I got this

**Comment by iamtrask** [comment]
Closed via https://github.com/OpenMined/syft.js/pull/16
