### ISSUE TITLE
Error: invalid wire type 4 at offset 2332

### ISSUE THREAD

**Issue by erksch** [OpenMined/syft.js#148]
### Description

I tried to run syft.js together with a hosted FL plan for MNIST that I created and hosted with the notebooks from the PySyft repo (`/examples/experimental/FL Training Plan`). I followed the instructions in the `syft.js` repo and opened the `with-grid` example. However when starting the worker, there seem to be a number of issues:

1. The upload speed test takes extremely long and blocks the whole machine. I had to manually kill my chrome process to exit the syft.js tab. This is weird because the 64MB buffer you created should not take too long to send to a localhost server. I solved this by just returning `Promise.resolve(1000)` in the `getUploadSpeed` function.
2. Next, unserializing the plan protobuf that is returned by the server fails with the following error:
``` 
Error: invalid wire type 4 at offset 2332
``` 
The unserialization of the model protobuf that is executed right before that works.

## How to Reproduce
1. Setup PyGrid and PySyft
2. Create and host a plan the PySyft notebook example
3. Setup syft.js
4. Click "Start FL Worker"

## System Information
 - OS: Ubuntu 
 - OS Version: 20.04
 - Language Version: Python 3.7, Node 10.14.2
 - Package Manager Version: pip 19.3. NPM 6.5

**Comment by cereallarceny** [comment]
We will look into this @erksch, sorry for the delay. @vvmnnnkv have you come across this?

**Comment by vvmnnnkv** [comment]
I've separated upload speed test problem in #150
@erksch could you put more details there?
Thanks!

**Comment by vvmnnnkv** [comment]
```Error: invalid wire type 4 at offset 2332```

Should be fixed by #151

**Comment by cereallarceny** [comment]
Closed by #151

**Comment by erksch** [comment]
Awesome! I'll give it a try.
