### ISSUE TITLE
Setup NPM publishing from Github actions

### ISSUE THREAD

**Issue by vvmnnnkv** [OpenMined/syft.js#160]
## Feature Description
Add github action to automatically publish github releases to NPM registry.

## Is your feature request related to a problem?
At the moment syft.js can only be installed from github directly, which is slow because all bundling occurs on the user's machine

## What alternatives have you considered?
Publishing manually - might be error prone.

## Additional Context
Same thing should be done for threepio and syft-proto javascript libraries, so it's better to have solution that will fit all 3 libraries.

**Comment by cereallarceny** [comment]
We’re not going to deploy this way anymore.
