### ISSUE TITLE
Namespace static FL routes

### ISSUE THREAD

**Issue by sachin-101** [OpenMined/syft.js#186]
## What?
Please, add prefix `/model_centric` to all the requests to grid. You can also get rid of the unnecessary `/federated` for all endpoints that have it as part of the url. Part of an effort to namespace static and dynamic API routes in PyGrid. 
#https://github.com/OpenMined/PyGrid/issues/600

Reference to PyGrid PR: https://github.com/OpenMined/PyGrid/pull/622

**Comment by cereallarceny** [comment]
Thanks for reporting @sachin-101. We need to wait on this until after Wednesday.
