### ISSUE TITLE
Use custom Error classes

### ISSUE THREAD

**Issue by vvmnnnkv** [OpenMined/syft.js#204]
## Description
Define custom Errors, so errors can be handled easier.
See this example in KotlinSyft: https://github.com/OpenMined/KotlinSyft/blame/dev/syftlib/src/main/java/org/openmined/syft/execution/JobErrorThrowable.kt

## Are you interested in working on this improvement yourself?
- Yes, I am.

## Additional Context
n/a

**Comment by shoniko** [comment]
I have started a PR here: https://github.com/OpenMined/syft.js/pull/223
