### ISSUE TITLE
Test syft.js main file

### ISSUE THREAD

**Issue by cereallarceny** [OpenMined/syft.js#60]
**The syft.js project could use a lot of help refining our current test suite.**

We need to test the syft.js file as it currently stands. This issue is a bit non-descript, so if you're interested in helping to write tests, please contact me (@cereallarceny) on Slack and I'll get you started!

**Comment by rav7kantsingh** [comment]
I would like to contribute to this issue.

**Comment by vvmnnnkv** [comment]
Main file is going to be changed to line up with federated learning roadmap. I think it's better to wait a bit on this one

**Comment by cereallarceny** [comment]
Yes, let's wait for a few more weeks.

**Comment by danyialkhan** [comment]
I like to contribute to this issue.

**Comment by cereallarceny** [comment]
We're waiting until the API has matured. Please wait to work on this issue until at least May.
