### ISSUE TITLE
Migrate all Serde tests to use live data from grid.js seed generator

### ISSUE THREAD

**Issue by cereallarceny** [OpenMined/syft.js#61]
**The syft.js project could use a lot of help refining our current test suite.**

Currently, all of our tests for Serde in Javascript run based on strings that we occasionally copy and paste from PySyft. However, these strings are now incredibly out of date and we're finding a lot of problems as the PySyft team changes things periodically. We need to figure out some sort of way to utilize the grid.js seed file generator (maybe by building one of our own in syft.js?) to automate the creation of these Serde simplified strings. **In theory, this would notify us every time syft.js becomes out of date with PySyft... aka, insanely helpful.**

This issue is a bit non-descript, so if you're interested in helping to write tests, please contact me (@cereallarceny) on Slack and I'll get you started!

**Comment by tsingh2k15** [comment]
@cereallarceny I would like to understand more and potentially contribute to solve this.

**Comment by cereallarceny** [comment]
Sorry @tsingh2k15, this issue isn't relevant anymore. Closing.
