### ISSUE TITLE
Add eslint support

### ISSUE THREAD

**Issue by cereallarceny** [OpenMined/syft.js#62]
We need help adding ESLint to syft.js so that we can more readily detect style issues in our code. Ideally, all configs would be set to error so that we have failing tests until the code is properly written.

This issue is a bit non-descript, so if you're interested in helping configuring ESLint properly, please contact me (@cereallarceny) on Slack and I'll get you started!

**Comment by cereallarceny** [comment]
Ideally we would use `eslint: recommended` with the `strict` rule set to `['error', 'never']`.

**Comment by ghost** [comment]
hi, i'd like to try this

**Comment by cereallarceny** [comment]
Alright @robertbegna!  It's yours.  Hit me up in Slack if you have questions.  I'm happy to assist.  :)
