### ISSUE TITLE
Convert Logger class to be a singleton

### ISSUE THREAD

**Issue by cereallarceny** [OpenMined/syft.js#63]
Right now, we have the `Logger` class as a class that you can create, but then you have to pass it around the library, or instantiate a new version each time. It would be a lot easier to convert this to be a singleton class. This would allow us to "instantiate" the `Logger` class multiple times, but only have one true reference to the first one we created. This also has a huge added benefit of not having to pass the original `Logger` instance (located in the `syft.js` file) around to each of the other files... annoying!

This is a really good first issue, any takers?

**Comment by 3lv27** [comment]
I already submitted a PR

**Comment by tsingh2k15** [comment]
@cereallarceny I have tried to make changes to support this function. Submitted a PR at https://github.com/OpenMined/syft.js/pull/106

**Comment by cereallarceny** [comment]
Replied in your PR @tsingh2k15

**Comment by vvmnnnkv** [comment]
Done in #106
