### ISSUE TITLE
Connecting PySyft's WebSocketWorker to syft.js

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/syft.js#7]
In the [PySyft Examples](https://github.com/OpenMined/PySyft/tree/master/examples/websocket) folder, you can see a demo where Python uses WebSockets to send and receive JSON commands.

In this project, we want to add the ability to receive JSON commands from a PySyft client and simply log them out to the screen.

**Comment by adgelbfish** [comment]
I going to start on this
