### ISSUE TITLE
Peer connections not closed

### ISSUE THREAD

**Issue by vkkhare** [OpenMined/syft.js#76]
[removePeer](https://github.com/OpenMined/syft.js/blob/master/src/webrtc.js#L42-L55) function when called only closes the data channel.

Shouldn't the peer connection should also get closed when the worker leaves or is removed?

**Comment by cereallarceny** [comment]
This should be done when the tab is closed or the worker loses connection, no?  I believe this is cleaned up by the browser.

**Comment by cereallarceny** [comment]
@vvmnnnkv Did we address this?
