### ISSUE TITLE
[syft.js] Force all insecure websocket connections to be secure

### ISSUE THREAD

**Issue by cereallarceny** [OpenMined/syft.js#77]
We need to ensure that all connections to a grid server are done via `wss` and NEVER `ws`. This could be as simple as including a string check against url supplied by the app.

**Comment by rav7kantsingh** [comment]
Can I work on this issue?

**Comment by cereallarceny** [comment]
Sure!

**Comment by vvmnnnkv** [comment]
Per latest discussions, I think we wanted to have a flag (disabled by default) that allows non-secure connections for debug/dev purposes.

**Comment by cereallarceny** [comment]
Correct, add a "debug" boolean value to the main syft class that when true,
it should allow insecure connections. When false (or undefined) force the
connection to be secure by automatically converting any "ws://" strings to
"wss://". This debug value should also used in the Logger class -
production shouldn't have the Logger output anything.  I think at the
moment this is called the "verbose" flag, but you can make it "debug" and
use them in both situations.

**Comment by vvmnnnkv** [comment]
Could you also make change in GridAPIClient? It's created in Syft constructor.
I think we can add option like `allowInsecureUrl` (default false) to GridAPIClient constructor and pass true when Syft is constructed with verbose=true?

**Comment by cereallarceny** [comment]
@vvmnnnkv I think @IamRavikantSingh did this in #111 - looks good to me. Ready to merge when you are.
