### ISSUE TITLE
Implement the command translation layer inside of syft.js

### ISSUE THREAD

**Issue by cereallarceny** [OpenMined/syft.js#86]
The Threepio project is set to replace the `convertToTF()` function in syft.ks. This function currently only provides rudimentary, and very naive, conversion of commands from PyTorch to TFJS. Threepio will focus on a 3-way translation for the majority of the commands in PyTorch, TensorFlow, and TFJS.

Once Threepio is in a good state, we'll want to include this library inside of syft.js to allow for plan command conversion on the fly and in any direction we choose.

The following issues must be completed first:
- https://github.com/OpenMined/threepio/issues/4
- https://github.com/OpenMined/threepio/issues/5

**Comment by vvmnnnkv** [comment]
@cereallarceny @Nolski Is that issue solved by #112?
