### ISSUE TITLE
Execute plans in syft.js

### ISSUE THREAD

**Issue by cereallarceny** [OpenMined/syft.js#89]
As of now, syft.js is entirely protocol based. Now that we have a new roadmap, we must shift focus to the execution of training plans. This will require initially translating a training plan's list of operations into operations that can be executed in TFJS. This work will be done for us by using Threepio.

Currently, the code we have in syft.js actually runs plans somewhat well, but they're always wrapped in a protocol. This old plan execution code will need to be migrated over after we develop the new API structure in syft.js (https://github.com/OpenMined/syft.js/issues/87).

**Comment by vvmnnnkv** [comment]
UPD: Plan execution is somewhat done, at least for FL purposes, but I'm not sure it covers everything that Plans can do outside of FL use case (e.g. pointer tensors). 
Also, it haven't been tested rigorously outside of FL MNIST example. 
So not sure we can close that right now.

**Comment by cereallarceny** [comment]
That's fine @vvmnnnkv, leave it open for now and we can address it later.

**Comment by karlhigley** [comment]
Not sure we're on the same page about what Plans can do. What use cases involve combining Plans and PointerTensors? Are we talking about cryptographic protocols that involve communication between workers?

**Comment by vvmnnnkv** [comment]
@karlhigley e.g. in PySyft `test_plan.py`, PointerTensor is fed into a Plan pointer. Maybe inside PySyft this results in tensor being fed into Plan, not sure.
