### ISSUE TITLE
Migrate syft.js from Travis to Github Actions

### ISSUE THREAD

**Issue by cereallarceny** [OpenMined/syft.js#94]
We're switching from using Travis to Github actions (https://github.com/OpenMined/PySyft/pull/3013). Please migrate this project to do so as well. It's important to also ensure that pull requests cannot be merged without an all-green CI report.

**Comment by Benardi** [comment]
I would like to work on this

**Comment by cereallarceny** [comment]
It's yours @Benardi!  @vvmnnnkv if you could provide him anything he needs to do this. :)
